/**
 * test-mcp/src/index.ts
 *
 * MCP server that generates property-based test stubs and reports test coverage.
 * The swarm-orchestrator calls this after implementation (Step 4).
 *
 * Tool: generate_and_run
 * Input:  { files: string[], strategy: "property-based" | "unit" | "integration" }
 * Output: { tests_generated: number, passed: boolean, coverage_pct: number, report: string }
 */

import * as http from "http";
import * as fs from "fs";
import * as path from "path";
import * as child_process from "child_process";

const PORT = parseInt(process.env.TEST_MCP_PORT ?? "3002", 10);
const REPO_ROOT = process.env.REPO_ROOT ?? process.cwd();

interface TestResult {
  tests_generated: number;
  passed: boolean;
  coverage_pct: number;
  report: string;
  generated_test_path?: string;
}

interface MCPRequest {
  tool: string;
  args: Record<string, unknown>;
  id?: string;
}

interface MCPResponse {
  id?: string;
  result?: unknown;
  error?: { code: number; message: string };
}

function detectLanguage(files: string[]): "typescript" | "python" | "unknown" {
  const exts = files.map((f) => path.extname(f).toLowerCase());
  if (exts.some((e) => e === ".ts" || e === ".tsx")) return "typescript";
  if (exts.some((e) => e === ".py")) return "python";
  return "unknown";
}

function generatePropertyTests(files: string[], lang: "typescript" | "python" | "unknown"): string {
  if (lang === "typescript") {
    return [
      `import fc from "fast-check";`,
      ``,
      `// Auto-generated property-based tests`,
      `// Files under test: ${files.join(", ")}`,
      ``,
      `describe("Property-based tests (auto-generated by test-mcp)", () => {`,
      `  it("should handle arbitrary valid inputs without throwing", () => {`,
      `    fc.assert(`,
      `      fc.property(fc.string(), fc.integer(), (str, num) => {`,
      `        // TODO: Replace with actual function calls from the implementation`,
      `        expect(typeof str).toBe("string");`,
      `        expect(typeof num).toBe("number");`,
      `      })`,
      `    );`,
      `  });`,
      ``,
      `  it("should satisfy idempotency where applicable", () => {`,
      `    fc.assert(`,
      `      fc.property(fc.string(), (input) => {`,
      `        // TODO: Assert f(f(x)) === f(x) for pure transform functions`,
      `        expect(input.length).toBeGreaterThanOrEqual(0);`,
      `      })`,
      `    );`,
      `  });`,
      `});`,
    ].join("\n");
  }

  if (lang === "python") {
    return [
      `"""Auto-generated property-based tests using Hypothesis"""`,
      `# Files under test: ${files.join(", ")}`,
      ``,
      `from hypothesis import given, strategies as st`,
      ``,
      `@given(st.text())`,
      `def test_handles_arbitrary_strings(s: str) -> None:`,
      `    """Property: function should not raise on any string input."""`,
      `    # TODO: Replace with actual function call`,
      `    assert isinstance(s, str)`,
      ``,
      `@given(st.integers())`,
      `def test_handles_arbitrary_integers(n: int) -> None:`,
      `    """Property: function should not raise on any integer input."""`,
      `    # TODO: Replace with actual function call`,
      `    assert isinstance(n, int)`,
    ].join("\n");
  }

  return `# No test generator available for language: ${lang}\n# Files: ${files.join(", ")}`;
}

function runTests(testPath: string, lang: "typescript" | "python" | "unknown"): { passed: boolean; output: string } {
  if (lang === "typescript") {
    // Use spawnSync with separate args to prevent command injection
    const result = child_process.spawnSync(
      "npx",
      ["jest", "--testPathPattern", testPath, "--coverage", "--no-cache"],
      { cwd: REPO_ROOT, timeout: 60000 }
    );
    const output = [
      result.stdout?.toString() ?? "",
      result.stderr?.toString() ?? "",
    ].join("\n");
    return { passed: result.status === 0, output };
  }
  if (lang === "python") {
    // Use spawnSync with separate args to prevent command injection
    const result = child_process.spawnSync(
      "python",
      ["-m", "pytest", testPath, "-v"],
      { cwd: REPO_ROOT, timeout: 60000 }
    );
    const output = [
      result.stdout?.toString() ?? "",
      result.stderr?.toString() ?? "",
    ].join("\n");
    return { passed: result.status === 0 && output.includes("passed"), output };
  }
  return { passed: false, output: "Unknown language — tests not run" };
}

async function generateAndRun(args: Record<string, unknown>): Promise<TestResult> {
  const files = Array.isArray(args.files) ? (args.files as string[]) : [];
  const strategy = String(args.strategy ?? "property-based");

  if (files.length === 0) {
    throw new Error("files array must not be empty");
  }

  const lang = detectLanguage(files);
  const testCode = generatePropertyTests(files, lang);

  const ext = lang === "python" ? ".py" : ".test.ts";
  const tmpDir = path.join(REPO_ROOT, ".test-mcp-tmp");
  fs.mkdirSync(tmpDir, { recursive: true });
  const testPath = path.join(tmpDir, `generated${ext}`);
  fs.writeFileSync(testPath, testCode);

  const { passed, output } = runTests(testPath, lang);

  // Extract rough coverage percentage from output
  const coverageMatch = output.match(/All files.*?(\d+(?:\.\d+)?)\s*\|/);
  const coverage_pct = coverageMatch ? parseFloat(coverageMatch[1]) : 0;

  return {
    tests_generated: (testCode.match(/it\(|def test_/g) ?? []).length,
    passed,
    coverage_pct,
    report: output.slice(0, 2000),
    generated_test_path: testPath,
  };
}

const server = http.createServer(async (req, res) => {
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "ok", server: "test-mcp", port: PORT }));
    return;
  }

  if (req.method !== "POST" || req.url !== "/mcp") {
    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "Not found. POST to /mcp" }));
    return;
  }

  const chunks: Buffer[] = [];
  req.on("data", (c: Buffer) => chunks.push(c));
  req.on("end", async () => {
    let body: MCPRequest;
    try {
      body = JSON.parse(Buffer.concat(chunks).toString());
    } catch {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Invalid JSON" }));
      return;
    }

    const response: MCPResponse = { id: body.id };

    try {
      if (body.tool !== "generate_and_run") {
        throw new Error(`Unknown tool: ${body.tool}. Available: generate_and_run`);
      }
      response.result = await generateAndRun(body.args ?? {});
    } catch (err: unknown) {
      // Log detailed error server-side; expose only a sanitized message to callers
      console.error("test-mcp error:", err);
      response.error = {
        code: -32000,
        message: err instanceof Error ? err.message.split("\n")[0].slice(0, 200) : "Internal server error",
      };
    }

    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify(response));
  });
});

server.listen(PORT, () => {
  console.log(`test-mcp listening on http://localhost:${PORT}/mcp`);
  console.log(`Health: http://localhost:${PORT}/health`);
});
